---
# Authenticate with Prism Central and Prism Element and store session cookies.
- name: Authenticate to Prism Central 
  uri:
    url: "{{ pc_api_url }}/clusters/list"
    body:
      kind: cluster
      sort_order: ASCENDING
      offset: 0
      length: 10
      sort_attribute: ''
    method: POST
    validate_certs: no
    force_basic_auth: yes
    body_format: json
    user: "{{ prism_user }}"
    password: "{{ prism_password }}"
    status_code: 200
    return_content: yes
  register: pc_login
  ignore_errors: yes

- name: Store session cookie for Prism Central
  set_fact:
    pc_session_cookie: "{{ pc_login.set_cookie }}"

- name: Debug | Print session cookie for Prism Central
  debug:
    msg: "Session cookie for Prism Central is {{ pc_session_cookie }}"
  when: global_debug|bool

- name: Authenticate to Prism Element 
  uri:
    url: "{{ pe_api_url }}/clusters"
    method: GET 
    validate_certs: no
    force_basic_auth: yes
    user: "{{ prism_user }}"
    password: "{{ prism_password }}"
    status_code: 200
    return_content: yes
  register: pe_login
  ignore_errors: yes

- name: Store session cookie for Prism Element
  set_fact:
    pe_session_cookie: "{{ pe_login.set_cookie }}"

- name: Debug | Print session cookie for Prism Element
  debug:
    msg: "Session cookie for Prism Element is {{ pe_session_cookie }}"
  when: global_debug|bool