---
# Calls Prism Central to obtain a list of images
# Returns a list of dictionaries containing the name and uuid of the images
# Example output:
# [
#   {'name': 'imageA', 'uuid': '00056e15-0223-d74a-497a-ecf4bbd9b8f0'},
#   {'name': 'imageB', 'uuid': '00056e15-0223-d74a-497a-ecf4bbd9b8f1'}
# ]

- name: Get Images list
  uri:
    url: "{{ pc_api_url }}/images/list"
    body:
      length: 100
      offset: 0
      filter: ""
    method: POST
    validate_certs: no
    body_format: json
    status_code: 200
    headers: 
      Cookie: "{{ pc_session_cookie }}"
  register: json_images_result
  ignore_errors: yes

- name: Store the image names/UUIDs
  set_fact:
    image_uuids: "{{ image_uuids | default([]) + [ {'name': item.spec.name, 'uuid': item.metadata.uuid } ] }}"
  with_items: "{{ json_images_result.json.entities }}"

- name: Debug | Print image names/UUIDs
  debug:
    msg: "Image names/uuids are: {{ image_uuids }}"
  when: global_debug|bool