---
# Update Cluster and VM(s) specifications with UUIDs for creation
- name: Define Cluster UUID to use from name
  set_fact:
    cluster_uuid: "{{ item['uuid'] }}"
  when: "item['name'] == cluster_name"
  loop: "{{ cluster_uuids }}"

- name: Update VM(s) specifications with subnet UUIDs 
  include: update_subnet_uuids.yml
  loop: "{{ user_vm_defs }}"
  loop_control:
    loop_var: my_vm

- name: Debug | Print updated VM(s) specifications with subnet UUIDs
  debug:
    msg: "Updated VM specifications with subnet UUIDs : {{ vm_defs_1 }}"
  when: global_debug|bool

- name: Update VM specifications with image UUIDs 
  include: update_image_uuids.yml
  loop: "{{ vm_defs_1 }}"
  loop_control:
    loop_var: my_vm

- name: Store updated VM(s) specifications
  set_fact:
    ntx_vm_defs: "{{ vm_defs_2 }}"

- name: Debug | Print final user VM(s) specifications for creation
  debug:
    msg: "VM(s) shall be created as per: {{ ntx_vm_defs }}"